[package]
name = "koruma-shared-lib"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
es-fluent = { workspace = true }
es-fluent-lang = { workspace = true }
strum = { features = [ "derive" ], workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }
