[workspace]
default-members = [ "crates/koruma" ]
members = [
  "crates/koruma",
  "crates/koruma-collection",
  "crates/koruma-core",
  "crates/koruma-derive",
  "crates/koruma-derive-core",
  "examples/readme",
  "web",
  "xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/koruma"
rust-version = "1.96"
version = "0.9.0"

[workspace.dependencies]
anyhow = "1.0"
attribute-dsl = "0.1"
bon = "3.9"
card-validate = "2.4"
clap = "4.5"
dioxus = { default-features = false, version = "0.7" }
dioxus-free-icons = { default-features = false, version = "0.10.0" }
dioxus-primitives = { default-features = false, git = "https://github.com/DioxusLabs/components", version = "0.0.1" }
email_address = "0.2"
es-fluent = "0.17"
es-fluent-build = "0.17"
es-fluent-lang = "0.17"
es-fluent-manager-dioxus = { default-features = false, version = "0.7" }
es-fluent-manager-embedded = "0.17"
fluent-syntax = "0.12"
heck = "0.5"
idna = "1.1"
insta = "1.46"
inventory = "0.3"
koruma = { path = "crates/koruma", version = "0.9.0" }
koruma-collection = { path = "crates/koruma-collection", version = "0.9.0" }
koruma-core = { path = "crates/koruma-core", version = "0.9.0" }
koruma-derive = { path = "crates/koruma-derive", version = "0.9.0" }
koruma-derive-core = { path = "crates/koruma-derive-core", version = "0.9.0" }
lsp-types = "0.97.0"
paste = "1.0"
phonenumber = "0.3"
prettyplease = "0.2"
proc-macro-crate = "3.5"
proc-macro-error2 = "2.0"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.12"
rust-embed = "8.11"
rust_decimal = "1.40"
serde_json = "1.0"
smallvec = "1.15"
stayhydated-dioxus = { git = "https://github.com/stayhydated/shared", rev = "12c0941370cc5faf774798b625d840c662930702" }
stayhydated-site = { git = "https://github.com/stayhydated/shared", rev = "12c0941370cc5faf774798b625d840c662930702" }
stayhydated-xtask = { git = "https://github.com/stayhydated/shared", rev = "12c0941370cc5faf774798b625d840c662930702" }
strum = "0.28"
syn = "2.0"
tempfile = "3"
trybuild = "1.0"
unic-langid = "0.9"
url = "2.5"
web = { path = "web" }

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
derive_partial_eq_without_eq = "warn"
err_expect = "warn"
incompatible_msrv = "deny"
iter_on_single_items = "warn"
needless_bool = "warn"
redundant_clone = "warn"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"
useless_conversion = "warn"
