[workspace]
default-members = [ "examples/collection-ratatui-native" ]
members = [
  "crates/koruma",
  "crates/koruma-collection",
  "crates/koruma-core",
  "crates/koruma-derive",
  "crates/koruma-derive-core",
  "examples/collection-ratatui-core",
  "examples/collection-ratatui-native",
  "examples/collection-ratatui-web",
  "examples/collection-dioxus-web",
  "examples/readme",
  "examples/shared-lib",
  "xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/stayhydated/koruma"
rust-version = "1.88"
version = "0.7.1"

[workspace.dependencies]
anyhow = "1.0"
bon = "3.9"
card-validate = "2.4"
clap = "4.5"
console_error_panic_hook = "0.1"
crossterm = "0.29"
derive-getters = "0.5"
dioxus = "0.7"
dioxus-primitives = { git = "https://github.com/DioxusLabs/components" }
email_address = "0.2"
es-fluent = "0.14"
es-fluent-lang = "0.14"
es-fluent-manager-embedded = "0.14"
fluent-syntax = "0.12"
heck = "0.5"
idna = "1.1"
insta = "1.46"
inventory = "0.3"
koruma = { path = "crates/koruma", version = "0.7.1" }
koruma-collection = { path = "crates/koruma-collection", version = "0.7.1" }
koruma-core = { path = "crates/koruma-core", version = "0.7.1" }
koruma-derive = { path = "crates/koruma-derive", version = "0.7.1" }
koruma-derive-core = { path = "crates/koruma-derive-core", version = "0.7.1" }
paste = "1.0"
phonenumber = "0.3"
prettyplease = "0.2"
proc-macro-error2 = "2.0"
proc-macro2 = "1.0"
quote = "1.0"
ratatui = { default-features = false, version = "0.30" }
ratzilla = "0.3"
regex = "1.12"
rust-embed = "8.11"
rust_decimal = "1.40"
smallvec = "1.15"
strum = "0.27"
syn = "2.0"
syn-cfg-attr = "0.1"
unic-langid = "0.9"
url = "2.5"
wasm-bindgen = "0.2"
mdbook = "0.4"
mdbook-admonish = "1.0"

[profile.dev]
codegen-units = 16
debug = "limited"
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[workspace.lints.rust]
unexpected_cfgs = { level = "deny" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
type_complexity = "allow"
uninlined_format_args = "allow"
unused_trait_names = "warn"
