preserve_hierarchy: true

files:
  - source: /crates/koruma-collection/i18n/en/**/*.ftl
    translation: /crates/koruma-collection/i18n/%locale%/koruma-collection/%original_file_name%
    skip_untranslated_strings: true
    skip_untranslated_files: true
