[workspace]
changelog_update = false
repo_url = "https://github.com/stayhydated/koruma"
release_always = true
release = false
git_tag_name = "{{ package }}-v{{ version }}"

[[package]]
name = "koruma-derive-core"
release = true

[[package]]
name = "koruma-derive"
release = true

[[package]]
name = "koruma-core"
release = true

[[package]]
name = "koruma"
release = true

[[package]]
name = "koruma-collection"
release = true
