[package]
name = "xtask"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { features = [ "derive" ], workspace = true }
fluent-syntax = { workspace = true }
heck = { workspace = true }
proc-macro2 = { features = [ "span-locations" ], workspace = true }
quote = { workspace = true }
stayhydated-xtask = { workspace = true }
syn = { features = [ "full" ], workspace = true }
web = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
