use heck::{ToSnakeCase, ToUpperCamelCase};
use quote::ToTokens;
use syn::{
    Error, Expr, GenericArgument, Ident, Path, PathArguments, Result, Type,
    parse::{Parse, ParseStream, discouraged::Speculative},
    spanned::Spanned,
};

use super::keywords::ReservedBuilderMethod;

/// Represents a single parsed validator configuration chain.
///
/// Validator configuration uses direct Rust method chains generated by
/// `#[koruma::validator]` and also supports fully-qualified validator paths like
/// `module::path::ValidatorName::<_>`.
///
/// # Examples
///
/// ```rust
/// use koruma_derive_core::ValidatorAttr;
///
/// let simple: ValidatorAttr = syn::parse_quote!(NonEmptyValidation);
/// assert_eq!(simple.name().to_string(), "NonEmptyValidation");
/// assert!(!simple.uses_type_inference());
///
/// let inferred: ValidatorAttr =
///     syn::parse_quote!(RangeValidation::<_>::min(0).max(100));
/// assert!(inferred.uses_type_inference());
/// assert_eq!(inferred.setter_calls().len(), 2);
///
/// let explicit: ValidatorAttr =
///     syn::parse_quote!(RangeValidation::<i32>::min(0).max(100));
/// assert!(explicit.has_explicit_type());
///
/// let full_path: ValidatorAttr =
///     syn::parse_quote!(validators::numeric::RangeValidation::<_>::min(0));
/// assert_eq!(full_path.path_name(), "validators::numeric::RangeValidation");
/// ```
#[derive(Clone, Debug)]
pub enum ValidatorSetterArg {
    /// A normal Rust expression passed directly to a generated validator setter.
    Expr(Expr),
}

impl ValidatorSetterArg {
    pub fn as_expr(&self) -> &Expr {
        match self {
            Self::Expr(expr) => expr,
        }
    }
}

impl ToTokens for ValidatorSetterArg {
    fn to_tokens(&self, tokens: &mut proc_macro2::TokenStream) {
        match self {
            Self::Expr(expr) => expr.to_tokens(tokens),
        }
    }
}

#[derive(Clone, Debug)]
pub struct BuilderMethodCall {
    /// The builder setter method name, such as `min` or `exclusive_max`.
    pub method: Ident,
    /// Positional typed arguments passed to the setter.
    pub args: Vec<ValidatorSetterArg>,
}

/// Type argument syntax used by a validator path.
#[derive(Clone, Debug)]
pub enum ValidatorTypeArg {
    /// No validator type argument was supplied.
    None,
    /// The validator used `::<_>` and should infer from the validation target.
    Infer,
    /// The validator supplied an explicit type argument.
    Explicit(Type),
}

#[derive(Clone, Debug)]
pub struct ValidatorAttr {
    /// The validator path, which may be a simple identifier or a full path.
    /// Examples: `StringLengthValidation`, `validators::normal::NumberRangeValidation`
    pub validator: Path,
    /// Parsed validator type argument syntax.
    pub type_arg: ValidatorTypeArg,
    /// Builder setter method calls collected from a direct validator chain.
    /// Used by `Validator::arg(value)...`.
    pub builder_methods: Vec<BuilderMethodCall>,
}

impl ValidatorAttr {
    /// Returns the simple name of the validator (the last segment of the path).
    /// Used for generating field names and enum variants.
    pub fn name(&self) -> &Ident {
        &self
            .validator
            .segments
            .last()
            .expect("path should have at least one segment")
            .ident
    }

    /// Returns the full validator path as written, without generic arguments.
    pub fn path_name(&self) -> String {
        self.validator
            .segments
            .iter()
            .map(|segment| segment.ident.to_string())
            .collect::<Vec<_>>()
            .join("::")
    }

    /// Returns a stable snake_case stem for generated field and getter names.
    ///
    /// This returns the fully qualified path flattened into snake_case.
    /// Callers that need to resolve collisions should combine this with
    /// additional disambiguation logic.
    pub fn codegen_snake_name(&self) -> String {
        self.validator
            .segments
            .iter()
            .map(|segment| segment.ident.to_string().to_snake_case())
            .collect::<Vec<_>>()
            .join("_")
    }

    /// Returns a stable UpperCamelCase stem for generated enum variants.
    ///
    /// This returns the fully qualified path flattened into UpperCamelCase.
    /// Callers that need to resolve collisions should combine this with
    /// additional disambiguation logic.
    pub fn codegen_upper_camel_name(&self) -> String {
        self.validator
            .segments
            .iter()
            .map(|segment| segment.ident.to_string().to_upper_camel_case())
            .collect::<Vec<_>>()
            .join("")
    }

    /// Returns whether this validator has any arguments.
    pub fn has_args(&self) -> bool {
        !self.builder_methods.is_empty()
    }

    /// Returns validator configuration as normalized builder setter calls.
    pub fn setter_calls(&self) -> &[BuilderMethodCall] {
        &self.builder_methods
    }

    /// Returns whether this validator uses type inference (`<_>` syntax).
    pub fn uses_type_inference(&self) -> bool {
        matches!(self.type_arg, ValidatorTypeArg::Infer)
    }

    /// Returns whether this validator has an explicit type parameter.
    pub fn has_explicit_type(&self) -> bool {
        self.explicit_type().is_some()
    }

    /// Returns the explicit validator type parameter when one was supplied.
    pub fn explicit_type(&self) -> Option<&Type> {
        match &self.type_arg {
            ValidatorTypeArg::Explicit(ty) => Some(ty),
            ValidatorTypeArg::None | ValidatorTypeArg::Infer => None,
        }
    }
}

impl Parse for ValidatorAttr {
    fn parse(input: ParseStream) -> Result<Self> {
        if let Some(attr) = try_parse_direct_validator(input)? {
            return Ok(attr);
        }

        Err(invalid_validator_syntax_error(input))
    }
}

fn try_parse_direct_validator(input: ParseStream) -> Result<Option<ValidatorAttr>> {
    let fork = input.fork();
    let expr: Expr = match fork.parse() {
        Ok(expr) => expr,
        Err(_) => return Ok(None),
    };

    let Some(_) = analyze_direct_validator_expr(&expr)? else {
        return Ok(None);
    };
    input.advance_to(&fork);

    let Some((validator, builder_methods)) = analyze_direct_validator_expr(&expr)? else {
        return Err(Error::new(expr.span(), "expected validator chain"));
    };

    let (validator, type_arg) = split_validator_path_type_args(validator)?;

    Ok(Some(ValidatorAttr {
        validator,
        type_arg,
        builder_methods,
    }))
}

fn invalid_validator_syntax_error(input: ParseStream) -> Error {
    Error::new(
        input.span(),
        "validator syntax requires a direct validator chain such as `RequiredValidation::<_>` or `RangeValidation::<_>::min(value).max(value)`; `::builder()` chains and constructor-style validator args like `Validator(field = value)` are not accepted",
    )
}

fn split_validator_path_type_args(mut validator: Path) -> Result<(Path, ValidatorTypeArg)> {
    let validator_span = validator.span();
    let last_segment = validator
        .segments
        .last_mut()
        .ok_or_else(|| Error::new(validator_span, "expected validator path"))?;

    let args = std::mem::replace(&mut last_segment.arguments, PathArguments::None);
    let type_arg = match args {
        PathArguments::None => ValidatorTypeArg::None,
        PathArguments::AngleBracketed(mut angle_args) => {
            if angle_args.args.len() != 1 {
                return Err(Error::new(
                    angle_args.span(),
                    "validator type syntax expects exactly one type argument",
                ));
            }

            let arg = angle_args.args.pop().expect("len checked").into_value();
            match arg {
                GenericArgument::Type(Type::Infer(_)) => ValidatorTypeArg::Infer,
                GenericArgument::Type(ty) => ValidatorTypeArg::Explicit(ty),
                _ => Err(Error::new(
                    arg.span(),
                    "validator type syntax expects a type argument",
                ))?,
            }
        },
        PathArguments::Parenthesized(args) => {
            return Err(Error::new(
                args.span(),
                "validator path does not support parenthesized arguments",
            ));
        },
    };

    Ok((validator, type_arg))
}

fn analyze_direct_validator_expr(expr: &Expr) -> Result<Option<(Path, Vec<BuilderMethodCall>)>> {
    match expr {
        Expr::Group(group) => analyze_direct_validator_expr(&group.expr),
        Expr::Paren(paren) => analyze_direct_validator_expr(&paren.expr),
        Expr::MethodCall(method_call) => {
            let Some((validator, mut builder_methods)) =
                analyze_direct_validator_expr(&method_call.receiver)?
            else {
                return Ok(None);
            };

            if let Some(method) = ReservedBuilderMethod::from_ident(&method_call.method) {
                let method_name = method_call.method.to_string();
                return Err(Error::new(
                    method_call.method.span(),
                    reserved_builder_method_error(method, &method_name),
                ));
            }

            builder_methods.push(BuilderMethodCall {
                method: method_call.method.clone(),
                args: method_call
                    .args
                    .iter()
                    .cloned()
                    .map(ValidatorSetterArg::Expr)
                    .collect(),
            });
            Ok(Some((validator, builder_methods)))
        },
        Expr::Call(call) => analyze_direct_validator_call_expr(call),
        Expr::Path(path) => Ok(Some((path.path.clone(), Vec::new()))),
        _ => Ok(None),
    }
}

fn analyze_direct_validator_call_expr(
    call: &syn::ExprCall,
) -> Result<Option<(Path, Vec<BuilderMethodCall>)>> {
    let func = match &*call.func {
        Expr::Group(group) => &group.expr,
        Expr::Paren(paren) => &paren.expr,
        other => other,
    };

    let Expr::Path(path_expr) = func else {
        return Ok(None);
    };

    let mut validator_path = path_expr.path.clone();
    let Some(last_segment) = validator_path.segments.last() else {
        return Ok(None);
    };
    let method = last_segment.ident.clone();
    if method
        .to_string()
        .chars()
        .next()
        .is_some_and(char::is_uppercase)
    {
        return Ok(None);
    }

    if let Some(reserved) = ReservedBuilderMethod::from_ident(&method) {
        if !reserved.is_builder() {
            return Err(Error::new(
                method.span(),
                reserved_builder_method_error(reserved, &method.to_string()),
            ));
        }

        return Err(Error::new(
            path_expr.path.span(),
            "validator `::builder()` syntax is not supported; use direct syntax such as `Validator::min(value)` or bare `Validator` for validators without configuration fields",
        ));
    }

    validator_path.segments.pop();
    validator_path.segments.pop_punct();
    if validator_path.segments.is_empty() {
        return Ok(None);
    }

    Ok(Some((
        validator_path,
        vec![BuilderMethodCall {
            method,
            args: call
                .args
                .iter()
                .cloned()
                .map(ValidatorSetterArg::Expr)
                .collect(),
        }],
    )))
}

fn reserved_builder_method_error(method: ReservedBuilderMethod, method_name: &str) -> String {
    if method.is_builder() {
        return "validator `::builder()` syntax is not supported; use direct syntax such as `Validator::min(value)` or bare `Validator` for validators without configuration fields"
            .to_owned();
    }

    format!(
        "validator chains should stop before `.{method_name}(...)`; koruma injects builder creation, value capture, and `.build()` automatically"
    )
}
