//! Parsing logic for `#[koruma(...)]` attributes.
//!
//! This module provides types and functions for parsing koruma validation
//! attributes from syn AST nodes.

use heck::{ToSnakeCase, ToUpperCamelCase};
use syn::{
    Attribute, Error, Expr, Field, Fields, GenericArgument, Ident, Index, ItemStruct, Member, Path,
    PathArguments, Result, Token, Type, parenthesized,
    parse::{Parse, ParseStream, discouraged::Speculative},
    spanned::Spanned,
    token,
};

use syn_cfg_attr::{AttributeHelpers, ExpandedAttr};

/// Attribute language supported by a specific koruma macro context.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum KorumaAttrContext {
    /// Struct-level `#[koruma(...)]` options on `#[derive(Koruma)]` data types.
    Struct,
    /// Field-level `#[koruma(...)]` options on `#[derive(Koruma)]` data fields.
    DataField,
    /// Field-level `#[koruma(...)]` markers inside `#[koruma::validator]` structs.
    ValidatorField,
    /// `#[showcase(...)]` validator metadata.
    Showcase,
}

impl KorumaAttrContext {
    fn name(self) -> &'static str {
        match self {
            KorumaAttrContext::Struct => "derive struct",
            KorumaAttrContext::DataField => "derive data field",
            KorumaAttrContext::ValidatorField => "validator field",
            KorumaAttrContext::Showcase => "showcase",
        }
    }

    fn accepted_items(self) -> &'static str {
        match self {
            KorumaAttrContext::Struct => "`try_new`, `newtype`, or `newtype(try_from)`",
            KorumaAttrContext::DataField => {
                "`skip`, `nested`, `newtype`, validators, or `each(...)`"
            },
            KorumaAttrContext::ValidatorField => {
                "`value`, `value(capture = skip)`, or `setter(...)`"
            },
            KorumaAttrContext::Showcase => {
                "`name`, `description`, `create`, `input_type`, or `module`"
            },
        }
    }
}

fn context_error(marker: &Ident, context: KorumaAttrContext) -> Error {
    Error::new(
        marker.span(),
        format!(
            "`{}` is not valid in a {} `#[koruma(...)]` attribute; expected {}",
            marker,
            context.name(),
            context.accepted_items()
        ),
    )
}

/// Represents a single parsed validator configuration chain.
///
/// Validator configuration uses direct Rust method chains generated by
/// `#[koruma::validator]` and also supports fully-qualified validator paths like
/// `module::path::ValidatorName::<_>`.
///
/// # Examples
///
/// ```rust
/// use koruma_derive_core::ValidatorAttr;
///
/// let simple: ValidatorAttr = syn::parse_quote!(NonEmptyValidation);
/// assert_eq!(simple.name().to_string(), "NonEmptyValidation");
/// assert!(!simple.uses_type_inference());
///
/// let inferred: ValidatorAttr =
///     syn::parse_quote!(RangeValidation::<_>::min(0).max(100));
/// assert!(inferred.uses_type_inference());
/// assert_eq!(inferred.setter_calls().len(), 2);
///
/// let explicit: ValidatorAttr =
///     syn::parse_quote!(RangeValidation::<i32>::min(0).max(100));
/// assert!(explicit.has_explicit_type());
///
/// let full_path: ValidatorAttr =
///     syn::parse_quote!(validators::numeric::RangeValidation::<_>::min(0));
/// assert_eq!(full_path.path_name(), "validators::numeric::RangeValidation");
/// ```
#[derive(Clone, Debug)]
pub struct BuilderMethodCall {
    /// The builder setter method name, such as `min` or `exclusive_max`.
    pub method: Ident,
    /// Positional Rust expression arguments passed to the setter.
    pub args: Vec<Expr>,
}

/// Type argument syntax used by a validator path.
#[derive(Clone, Debug)]
pub enum ValidatorTypeArg {
    /// No validator type argument was supplied.
    None,
    /// The validator used `::<_>` and should infer from the validation target.
    Infer,
    /// The validator supplied an explicit type argument.
    Explicit(Type),
}

/// Target selection policy for optional validation targets.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum TargetPolicy {
    /// Default behavior: validators receive the inner `T` for `Option<T>`.
    UnwrapOption,
    /// Validators receive the full field or element target.
    FullTarget,
}

#[derive(Clone, Debug)]
pub struct ValidatorAttr {
    /// The validator path, which may be a simple identifier or a full path.
    /// Examples: `StringLengthValidation`, `validators::normal::NumberRangeValidation`
    pub validator: Path,
    /// Parsed validator type argument syntax.
    pub type_arg: ValidatorTypeArg,
    /// Whether this validator receives the full target or koruma's default
    /// optional-unwrapped target.
    pub target_policy: TargetPolicy,
    /// Builder setter method calls collected from a direct validator chain.
    /// Used by `Validator::arg(value)...`.
    pub builder_methods: Vec<BuilderMethodCall>,
}

impl ValidatorAttr {
    /// Returns the simple name of the validator (the last segment of the path).
    /// Used for generating field names and enum variants.
    pub fn name(&self) -> &Ident {
        &self
            .validator
            .segments
            .last()
            .expect("path should have at least one segment")
            .ident
    }

    /// Returns the full validator path as written, without generic arguments.
    pub fn path_name(&self) -> String {
        self.validator
            .segments
            .iter()
            .map(|segment| segment.ident.to_string())
            .collect::<Vec<_>>()
            .join("::")
    }

    /// Returns a stable snake_case stem for generated field and getter names.
    ///
    /// This returns the fully qualified path flattened into snake_case.
    /// Callers that need to resolve collisions should combine this with
    /// additional disambiguation logic.
    pub fn codegen_snake_name(&self) -> String {
        self.validator
            .segments
            .iter()
            .map(|segment| segment.ident.to_string().to_snake_case())
            .collect::<Vec<_>>()
            .join("_")
    }

    /// Returns a stable UpperCamelCase stem for generated enum variants.
    ///
    /// This returns the fully qualified path flattened into UpperCamelCase.
    /// Callers that need to resolve collisions should combine this with
    /// additional disambiguation logic.
    pub fn codegen_upper_camel_name(&self) -> String {
        self.validator
            .segments
            .iter()
            .map(|segment| segment.ident.to_string().to_upper_camel_case())
            .collect::<Vec<_>>()
            .join("")
    }

    /// Returns whether this validator has any arguments.
    pub fn has_args(&self) -> bool {
        !self.builder_methods.is_empty()
    }

    /// Returns validator configuration as normalized builder setter calls.
    pub fn setter_calls(&self) -> &[BuilderMethodCall] {
        &self.builder_methods
    }

    /// Returns whether this validator uses type inference (`<_>` syntax).
    pub fn uses_type_inference(&self) -> bool {
        matches!(self.type_arg, ValidatorTypeArg::Infer)
    }

    /// Returns whether this validator has an explicit type parameter.
    pub fn has_explicit_type(&self) -> bool {
        self.explicit_type().is_some()
    }

    /// Returns the explicit validator type parameter when one was supplied.
    pub fn explicit_type(&self) -> Option<&Type> {
        match &self.type_arg {
            ValidatorTypeArg::Explicit(ty) => Some(ty),
            ValidatorTypeArg::None | ValidatorTypeArg::Infer => None,
        }
    }

    /// Returns whether this validator was wrapped in `full(...)`.
    pub fn wants_full_target(&self) -> bool {
        self.target_policy == TargetPolicy::FullTarget
    }
}

impl Parse for ValidatorAttr {
    fn parse(input: ParseStream) -> Result<Self> {
        if let Some(attr) = try_parse_full_validator(input)? {
            return Ok(attr);
        }

        if let Some(attr) = try_parse_direct_validator(input)? {
            return Ok(attr);
        }

        Err(invalid_validator_syntax_error(input))
    }
}

fn try_parse_full_validator(input: ParseStream) -> Result<Option<ValidatorAttr>> {
    if !input.peek(Ident) {
        return Ok(None);
    }

    let fork = input.fork();
    let ident: Ident = fork.parse()?;
    if ident != "full" || !fork.peek(token::Paren) {
        return Ok(None);
    }

    input.parse::<Ident>()?;
    let content;
    parenthesized!(content in input);
    if content.is_empty() {
        return Err(Error::new(
            content.span(),
            "`full(...)` must contain exactly one validator",
        ));
    }

    let mut attr = content.parse::<ValidatorAttr>()?;
    if attr.target_policy == TargetPolicy::FullTarget {
        return Err(Error::new(
            ident.span(),
            "`full(...)` cannot be nested inside another `full(...)` wrapper",
        ));
    }
    if !content.is_empty() {
        return Err(Error::new(
            content.span(),
            "`full(...)` must contain exactly one validator",
        ));
    }

    attr.target_policy = TargetPolicy::FullTarget;
    Ok(Some(attr))
}

fn try_parse_direct_validator(input: ParseStream) -> Result<Option<ValidatorAttr>> {
    let fork = input.fork();
    let expr: Expr = match fork.parse() {
        Ok(expr) => expr,
        Err(_) => return Ok(None),
    };

    let Some(_) = analyze_direct_validator_expr(&expr)? else {
        return Ok(None);
    };
    input.advance_to(&fork);

    let Some((validator, builder_methods)) = analyze_direct_validator_expr(&expr)? else {
        return Err(Error::new(expr.span(), "expected validator chain"));
    };

    let (validator, type_arg) = split_validator_path_type_args(validator)?;

    Ok(Some(ValidatorAttr {
        validator,
        type_arg,
        target_policy: TargetPolicy::UnwrapOption,
        builder_methods,
    }))
}

fn invalid_validator_syntax_error(input: ParseStream) -> Error {
    Error::new(
        input.span(),
        "validator syntax requires a direct validator chain such as `full(RequiredValidation::<_>)` or `RangeValidation::<_>::min(value).max(value)`; `::builder()` chains and constructor-style validator args like `Validator(field = value)` are not accepted",
    )
}

fn split_validator_path_type_args(mut validator: Path) -> Result<(Path, ValidatorTypeArg)> {
    let validator_span = validator.span();
    let last_segment = validator
        .segments
        .last_mut()
        .ok_or_else(|| Error::new(validator_span, "expected validator path"))?;

    let args = std::mem::replace(&mut last_segment.arguments, PathArguments::None);
    let type_arg = match args {
        PathArguments::None => ValidatorTypeArg::None,
        PathArguments::AngleBracketed(mut angle_args) => {
            if angle_args.args.len() != 1 {
                return Err(Error::new(
                    angle_args.span(),
                    "validator type syntax expects exactly one type argument",
                ));
            }

            let arg = angle_args.args.pop().expect("len checked").into_value();
            match arg {
                GenericArgument::Type(Type::Infer(_)) => ValidatorTypeArg::Infer,
                GenericArgument::Type(ty) => ValidatorTypeArg::Explicit(ty),
                _ => Err(Error::new(
                    arg.span(),
                    "validator type syntax expects a type argument",
                ))?,
            }
        },
        PathArguments::Parenthesized(args) => {
            return Err(Error::new(
                args.span(),
                "validator path does not support parenthesized arguments",
            ));
        },
    };

    Ok((validator, type_arg))
}

fn analyze_direct_validator_expr(expr: &Expr) -> Result<Option<(Path, Vec<BuilderMethodCall>)>> {
    match expr {
        Expr::Group(group) => analyze_direct_validator_expr(&group.expr),
        Expr::Paren(paren) => analyze_direct_validator_expr(&paren.expr),
        Expr::MethodCall(method_call) => {
            let Some((validator, mut builder_methods)) =
                analyze_direct_validator_expr(&method_call.receiver)?
            else {
                return Ok(None);
            };

            let method_name = method_call.method.to_string();
            if matches!(
                method_name.as_str(),
                "builder" | "build" | "with_value" | "capture_value_ref"
            ) {
                return Err(Error::new(
                    method_call.method.span(),
                    format!(
                        "validator chains should stop before `.{method_name}(...)`; koruma injects builder creation, value capture, and `.build()` automatically"
                    ),
                ));
            }

            builder_methods.push(BuilderMethodCall {
                method: method_call.method.clone(),
                args: method_call.args.iter().cloned().collect(),
            });
            Ok(Some((validator, builder_methods)))
        },
        Expr::Call(call) => analyze_direct_validator_call_expr(call),
        Expr::Path(path) => Ok(Some((path.path.clone(), Vec::new()))),
        _ => Ok(None),
    }
}

fn analyze_direct_validator_call_expr(
    call: &syn::ExprCall,
) -> Result<Option<(Path, Vec<BuilderMethodCall>)>> {
    let func = match &*call.func {
        Expr::Group(group) => &group.expr,
        Expr::Paren(paren) => &paren.expr,
        other => other,
    };

    let Expr::Path(path_expr) = func else {
        return Ok(None);
    };

    let mut validator_path = path_expr.path.clone();
    let Some(last_segment) = validator_path.segments.last() else {
        return Ok(None);
    };
    let method = last_segment.ident.clone();
    if method
        .to_string()
        .chars()
        .next()
        .is_some_and(char::is_uppercase)
    {
        return Ok(None);
    }

    if method == "builder" {
        return Err(Error::new(
            path_expr.path.span(),
            "validator `::builder()` syntax is not supported; use direct syntax such as `Validator::min(value)` or bare `Validator` for validators without configuration fields",
        ));
    }

    if matches!(
        method.to_string().as_str(),
        "build" | "with_value" | "capture_value_ref"
    ) {
        return Err(Error::new(
            method.span(),
            format!(
                "validator chains should stop before `.{method}(...)`; koruma injects builder creation, value capture, and `.build()` automatically"
            ),
        ));
    }

    validator_path.segments.pop();
    validator_path.segments.pop_punct();
    if validator_path.segments.is_empty() {
        return Ok(None);
    }

    Ok(Some((
        validator_path,
        vec![BuilderMethodCall {
            method,
            args: call.args.iter().cloned().collect(),
        }],
    )))
}

/// Field-level modifier parsed from `#[koruma(...)]`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FieldModifierKind {
    Skip,
    Nested,
    Newtype,
}

/// A parsed field-level modifier inside `#[koruma(...)]`.
#[derive(Clone, Debug)]
pub struct FieldModifier {
    pub kind: FieldModifierKind,
    pub ident: Ident,
}

/// A parsed validator occurrence inside a data-field `#[koruma(...)]` attribute.
#[derive(Clone, Debug)]
pub struct ParsedValidatorUse {
    pub validator: ValidatorAttr,
    pub label: Option<Ident>,
    pub source_span: proc_macro2::Span,
}

impl ParsedValidatorUse {
    pub fn unlabeled(validator: ValidatorAttr) -> Self {
        let source_span = validator.validator.span();
        Self {
            validator,
            label: None,
            source_span,
        }
    }

    pub fn labeled(label: Ident, validator: ValidatorAttr) -> Self {
        let source_span = validator.validator.span();
        Self {
            validator,
            label: Some(label),
            source_span,
        }
    }

    pub fn label_span(&self) -> Option<proc_macro2::Span> {
        self.label.as_ref().map(Spanned::span)
    }
}

/// A parsed direct field validator inside `#[koruma(...)]`.
#[derive(Clone, Debug)]
pub struct FieldValidationSpec {
    pub validator: ParsedValidatorUse,
}

/// A parsed `each(...)` element-validation block inside `#[koruma(...)]`.
#[derive(Clone, Debug)]
pub struct ElementValidationSpec {
    pub marker: Ident,
    pub validators: Vec<ParsedValidatorUse>,
}

/// A single typed item inside data-field `#[koruma(...)]`.
#[derive(Clone, Debug)]
pub enum DataFieldKorumaItem {
    Modifier(FieldModifier),
    FieldValidation(FieldValidationSpec),
    ElementValidation(ElementValidationSpec),
}

/// Represents a parsed data-field `#[koruma(...)]` attribute which can contain multiple validators
/// separated by commas: `#[koruma(Validator1::a(1), Validator2)]`
///
/// Can also include:
/// - `each(...)` modifier for collection validation
/// - `skip` to skip validation for a field
/// - `nested` to validate nested structs that also derive Koruma
/// - `newtype` to validate a newtype wrapper with transparent error access
///
/// # Examples
///
/// ```rust
/// use koruma_derive_core::DataFieldKorumaAttr;
///
/// let multiple: DataFieldKorumaAttr = syn::parse_quote!(
///     Validator1::a(1),
///     Validator2::b(2)
/// );
/// assert_eq!(multiple.field_validator_count(), 2);
///
/// let with_each: DataFieldKorumaAttr = syn::parse_quote!(
///     VecValidator::min(0),
///     each(ElementValidator::max(100))
/// );
/// assert_eq!(with_each.field_validator_count(), 1);
/// assert_eq!(with_each.element_validator_count(), 1);
///
/// let skip: DataFieldKorumaAttr = syn::parse_quote!(skip);
/// assert!(skip.is_skip());
///
/// let nested: DataFieldKorumaAttr = syn::parse_quote!(nested);
/// assert!(nested.is_nested());
/// ```
#[derive(Clone, Debug, Default)]
pub struct DataFieldKorumaAttr {
    pub items: Vec<DataFieldKorumaItem>,
}

impl DataFieldKorumaAttr {
    /// Returns whether this attribute has any validators (field or element).
    pub fn has_validators(&self) -> bool {
        self.items.iter().any(|item| match item {
            DataFieldKorumaItem::FieldValidation(_) => true,
            DataFieldKorumaItem::ElementValidation(spec) => !spec.validators.is_empty(),
            DataFieldKorumaItem::Modifier(_) => false,
        })
    }

    /// Returns whether this attribute represents a modifier (skip, nested, newtype).
    pub fn is_modifier(&self) -> bool {
        self.items
            .iter()
            .any(|item| matches!(item, DataFieldKorumaItem::Modifier(_)))
    }

    pub fn is_skip(&self) -> bool {
        self.items.iter().any(|item| {
            matches!(
                item,
                DataFieldKorumaItem::Modifier(FieldModifier {
                    kind: FieldModifierKind::Skip,
                    ..
                })
            )
        })
    }

    pub fn is_nested(&self) -> bool {
        self.items.iter().any(|item| {
            matches!(
                item,
                DataFieldKorumaItem::Modifier(FieldModifier {
                    kind: FieldModifierKind::Nested,
                    ..
                })
            )
        })
    }

    pub fn is_newtype(&self) -> bool {
        self.items.iter().any(|item| {
            matches!(
                item,
                DataFieldKorumaItem::Modifier(FieldModifier {
                    kind: FieldModifierKind::Newtype,
                    ..
                })
            )
        })
    }

    pub fn field_validators(&self) -> impl Iterator<Item = &ValidatorAttr> {
        self.items.iter().filter_map(|item| match item {
            DataFieldKorumaItem::FieldValidation(spec) => Some(&spec.validator.validator),
            DataFieldKorumaItem::Modifier(_) | DataFieldKorumaItem::ElementValidation(_) => None,
        })
    }

    pub fn element_validators(&self) -> impl Iterator<Item = &ValidatorAttr> {
        self.items.iter().flat_map(|item| {
            match item {
                DataFieldKorumaItem::ElementValidation(spec) => spec.validators.as_slice(),
                DataFieldKorumaItem::Modifier(_) | DataFieldKorumaItem::FieldValidation(_) => &[],
            }
            .iter()
            .map(|validator_use| &validator_use.validator)
        })
    }

    pub fn field_validator_count(&self) -> usize {
        self.field_validators().count()
    }

    pub fn element_validator_count(&self) -> usize {
        self.element_validators().count()
    }

    pub fn has_field_validators(&self) -> bool {
        self.field_validators().next().is_some()
    }

    pub fn has_element_validators(&self) -> bool {
        self.element_validators().next().is_some()
    }
}

impl DataFieldKorumaItem {
    pub fn modifier(&self) -> Option<FieldModifierKind> {
        match self {
            DataFieldKorumaItem::Modifier(modifier) => Some(modifier.kind),
            DataFieldKorumaItem::FieldValidation(_) | DataFieldKorumaItem::ElementValidation(_) => {
                None
            },
        }
    }
}

impl Parse for DataFieldKorumaAttr {
    fn parse(input: ParseStream) -> Result<Self> {
        if input.is_empty() {
            return Err(Error::new(
                input.span(),
                "`#[koruma(...)]` must contain a modifier, validator, or `each(...)` block",
            ));
        }

        let mut attr = DataFieldKorumaAttr::default();

        // Parse comma-separated items (validators or each(...))
        while !input.is_empty() {
            if let Some(modifier) = try_parse_field_modifier(input)? {
                attr.items.push(DataFieldKorumaItem::Modifier(modifier));
            } else if let Some(item) = try_parse_each(input)? {
                attr.items.push(item);
            } else {
                attr.items
                    .push(DataFieldKorumaItem::FieldValidation(FieldValidationSpec {
                        validator: parse_validator_use(input)?,
                    }));
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            } else {
                break;
            }
        }

        Ok(attr)
    }
}

fn try_parse_field_modifier(input: ParseStream) -> Result<Option<FieldModifier>> {
    if !input.peek(Ident) {
        return Ok(None);
    }

    let fork = input.fork();
    let ident: Ident = fork.parse()?;
    if matches!(
        ident.to_string().as_str(),
        "value" | "skip_capture" | "try_new"
    ) {
        return Err(context_error(&ident, KorumaAttrContext::DataField));
    }

    let kind = if ident == "skip" {
        FieldModifierKind::Skip
    } else if ident == "nested" {
        FieldModifierKind::Nested
    } else if ident == "newtype" {
        FieldModifierKind::Newtype
    } else {
        return Ok(None);
    };

    if fork.peek(token::Paren) {
        return Err(Error::new(
            ident.span(),
            format!(
                "`{ident}(...)` is not valid in a derive data field `#[koruma(...)]` attribute; expected {}",
                KorumaAttrContext::DataField.accepted_items()
            ),
        ));
    }

    if fork.peek(Token![::]) {
        return Err(Error::new(
            ident.span(),
            format!(
                "`{ident}` is a reserved koruma field modifier; use a different validator path or separate `newtype` from validators with a comma"
            ),
        ));
    }

    if !fork.is_empty() && !fork.peek(Token![,]) {
        return Ok(None);
    }

    let ident = input.parse::<Ident>()?;
    Ok(Some(FieldModifier { kind, ident }))
}

fn parse_validator_use(input: ParseStream) -> Result<ParsedValidatorUse> {
    if input.peek(Ident) {
        let fork = input.fork();
        let label: Ident = fork.parse()?;
        if fork.peek(Token![=]) {
            input.parse::<Ident>()?;
            input.parse::<Token![=]>()?;
            return Ok(ParsedValidatorUse::labeled(
                label,
                input.parse::<ValidatorAttr>()?,
            ));
        }
    }

    Ok(ParsedValidatorUse::unlabeled(
        input.parse::<ValidatorAttr>()?,
    ))
}

fn try_parse_each(input: ParseStream) -> Result<Option<DataFieldKorumaItem>> {
    if !input.peek(Ident) {
        return Ok(None);
    }

    let fork = input.fork();
    let ident: Ident = fork.parse()?;
    if ident != "each" || !fork.peek(token::Paren) {
        if ident == "each" && !fork.peek(Token![::]) {
            return Err(Error::new(
                ident.span(),
                "`each` is only valid as `each(...)` in a derive data field `#[koruma(...)]` attribute",
            ));
        }
        return Ok(None);
    }

    let marker = input.parse::<Ident>()?;
    let content;
    parenthesized!(content in input);
    if content.is_empty() {
        return Err(Error::new(
            content.span(),
            "`each(...)` must contain at least one validator",
        ));
    }

    let mut validators = Vec::new();
    while !content.is_empty() {
        validators.push(parse_validator_use(&content)?);
        if content.peek(Token![,]) {
            content.parse::<Token![,]>()?;
        } else {
            break;
        }
    }

    Ok(Some(DataFieldKorumaItem::ElementValidation(
        ElementValidationSpec { marker, validators },
    )))
}

/// Struct-level options parsed from `#[koruma(...)]`
///
/// # Examples
///
/// ```rust
/// use koruma_derive_core::parse_struct_options;
/// use syn::ItemStruct;
///
/// let user: ItemStruct = syn::parse_quote! {
///     #[koruma(try_new)]
///     struct User { name: String }
/// };
/// let options = parse_struct_options(&user.attrs).unwrap();
/// assert!(options.try_new());
/// assert!(!options.is_newtype());
///
/// let email: ItemStruct = syn::parse_quote! {
///     #[koruma(newtype)]
///     struct Email(String);
/// };
/// let options = parse_struct_options(&email.attrs).unwrap();
/// assert!(options.is_newtype());
/// assert!(!options.try_from());
///
/// let checked_email: ItemStruct = syn::parse_quote! {
///     #[koruma(try_new, newtype)]
///     struct CheckedEmail(String);
/// };
/// let options = parse_struct_options(&checked_email.attrs).unwrap();
/// assert!(options.try_new());
/// assert!(options.is_newtype());
///
/// let convertible_email: ItemStruct = syn::parse_quote! {
///     #[koruma(newtype(try_from))]
///     struct ConvertibleEmail(String);
/// };
/// let options = parse_struct_options(&convertible_email.attrs).unwrap();
/// assert!(options.is_newtype());
/// assert!(options.try_from());
/// ```
#[derive(Clone, Debug)]
pub struct StructOptions {
    /// Constructor integrations requested at the struct level.
    constructor: StructConstructor,
    /// Whether struct-level newtype behavior is enabled.
    newtype: bool,
}

impl Default for StructOptions {
    fn default() -> Self {
        Self {
            constructor: StructConstructor::None,
            newtype: false,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StructConstructor {
    None,
    TryNew,
    TryFrom,
    TryNewAndTryFrom,
}

impl StructConstructor {
    fn with_try_new(self) -> Self {
        match self {
            Self::None => Self::TryNew,
            Self::TryNew | Self::TryNewAndTryFrom => self,
            Self::TryFrom => Self::TryNewAndTryFrom,
        }
    }

    fn with_try_from(self) -> Self {
        match self {
            Self::None => Self::TryFrom,
            Self::TryFrom | Self::TryNewAndTryFrom => self,
            Self::TryNew => Self::TryNewAndTryFrom,
        }
    }

    pub fn try_new(self) -> bool {
        matches!(self, Self::TryNew | Self::TryNewAndTryFrom)
    }

    pub fn try_from(self) -> bool {
        matches!(self, Self::TryFrom | Self::TryNewAndTryFrom)
    }
}

impl StructOptions {
    pub fn constructor(&self) -> StructConstructor {
        self.constructor
    }

    pub fn is_newtype(&self) -> bool {
        self.newtype
    }

    pub fn try_new(&self) -> bool {
        self.constructor.try_new()
    }

    pub fn try_from(&self) -> bool {
        self.constructor.try_from()
    }
}

/// A single typed item inside struct-level `#[koruma(...)]`.
#[derive(Clone, Debug)]
pub enum StructKorumaItem {
    TryNew,
    Newtype(StructNewtypeOptions),
}

/// Options for the struct-level `newtype(...)` attribute.
#[derive(Clone, Debug, Default)]
pub struct StructNewtypeOptions {
    pub try_from: bool,
}

#[derive(Clone, Debug, Default)]
pub struct StructKorumaAttr {
    pub items: Vec<StructKorumaItem>,
}

impl Parse for StructNewtypeOptions {
    fn parse(input: ParseStream) -> Result<Self> {
        let mut options = StructNewtypeOptions::default();

        while !input.is_empty() {
            let ident: Ident = input.parse()?;
            match ident.to_string().as_str() {
                "try_from" => options.try_from = true,
                other => {
                    return Err(Error::new(
                        ident.span(),
                        format!("unknown newtype option: `{}`. Expected `try_from`", other),
                    ));
                },
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(options)
    }
}

impl Parse for StructKorumaAttr {
    fn parse(input: ParseStream) -> Result<Self> {
        let mut attr = StructKorumaAttr::default();

        while !input.is_empty() {
            let ident: Ident = input.parse()?;
            match ident.to_string().as_str() {
                "try_new" => {
                    if input.peek(token::Paren) || input.peek(Token![::]) {
                        return Err(Error::new(
                            ident.span(),
                            format!(
                                "`{ident}` is only valid as a bare struct-level `#[koruma(...)]` option; expected {}",
                                KorumaAttrContext::Struct.accepted_items()
                            ),
                        ));
                    }
                    attr.items.push(StructKorumaItem::TryNew);
                },
                "newtype" => {
                    let mut newtype_options = StructNewtypeOptions::default();
                    if input.peek(syn::token::Paren) {
                        let content;
                        syn::parenthesized!(content in input);
                        newtype_options = content.parse()?;
                    } else if input.peek(Token![::]) {
                        return Err(Error::new(
                            ident.span(),
                            format!(
                                "`{ident}` is a reserved koruma struct option; use a different validator path in a data-field `#[koruma(...)]` attribute"
                            ),
                        ));
                    }
                    attr.items.push(StructKorumaItem::Newtype(newtype_options));
                },
                other => {
                    if matches!(other, "skip" | "nested" | "each" | "value" | "skip_capture") {
                        return Err(context_error(&ident, KorumaAttrContext::Struct));
                    }
                    return Err(Error::new(
                        ident.span(),
                        format!(
                            "unknown struct-level koruma option: `{}`. Expected `try_new` or `newtype`",
                            other
                        ),
                    ));
                },
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(attr)
    }
}

impl Parse for StructOptions {
    fn parse(input: ParseStream) -> Result<Self> {
        let attr: StructKorumaAttr = input.parse()?;
        let mut options = StructOptions::default();

        for item in attr.items {
            match item {
                StructKorumaItem::TryNew => {
                    options.constructor = options.constructor.with_try_new();
                },
                StructKorumaItem::Newtype(newtype_options) => {
                    options.newtype = true;
                    if newtype_options.try_from {
                        options.constructor = options.constructor.with_try_from();
                    }
                },
            }
        }

        Ok(options)
    }
}

/// Parse struct-level `#[koruma(...)]` attributes from a list of attributes.
///
/// Returns `StructOptions::default()` if no `#[koruma(...)]` attribute is found.
pub fn parse_struct_options(attrs: &[Attribute]) -> Result<StructOptions> {
    let mut merged = StructOptions::default();

    for attr in attrs.to_vec().find_attribute("koruma") {
        let parsed = attr.parse_args::<StructOptions>()?;

        if parsed.try_new() {
            if merged.try_new() {
                return Err(Error::new(
                    attr.path().span(),
                    "duplicate struct-level koruma option `try_new`",
                ));
            }
            merged.constructor = merged.constructor.with_try_new();
        }

        if parsed.is_newtype() {
            if merged.is_newtype() {
                return Err(Error::new(
                    attr.path().span(),
                    "duplicate struct-level koruma option `newtype`",
                ));
            }
            merged.newtype = true;
            if parsed.try_from() {
                merged.constructor = merged.constructor.with_try_from();
            }
        }
    }

    Ok(merged)
}

/// Parsed field metadata extracted from all `#[koruma(...)]` attributes on a field.
#[derive(Clone, Debug)]
pub enum ParsedFieldSpec {
    Skipped,
    Regular {
        field_validators: Vec<ParsedValidatorUse>,
        element_validators: Vec<ParsedValidatorUse>,
    },
    Nested {
        marker: Ident,
    },
    Newtype {
        marker: Ident,
        field_validators: Vec<ParsedValidatorUse>,
    },
}

/// Field information extracted from parsing `#[koruma(...)]` attributes.
///
/// This struct contains all the parsed validation information for a single field,
/// including validators, element validators (for collection), and modifier flags.
#[derive(Clone, Debug)]
pub struct FieldInfo {
    /// The field name
    pub name: Ident,
    /// The struct member access (Named or Unnamed index)
    pub member: Member,
    /// The field type
    pub ty: Type,
    /// The original zero-based field index in the struct declaration.
    pub index: usize,
    /// Validation info for this field
    pub validation: ParsedFieldSpec,
}

impl FieldInfo {
    pub fn field_validators(&self) -> &[ParsedValidatorUse] {
        match &self.validation {
            ParsedFieldSpec::Regular {
                field_validators, ..
            }
            | ParsedFieldSpec::Newtype {
                field_validators, ..
            } => field_validators,
            ParsedFieldSpec::Skipped | ParsedFieldSpec::Nested { .. } => &[],
        }
    }

    pub fn element_validators(&self) -> &[ParsedValidatorUse] {
        match &self.validation {
            ParsedFieldSpec::Regular {
                element_validators, ..
            } => element_validators,
            ParsedFieldSpec::Skipped
            | ParsedFieldSpec::Nested { .. }
            | ParsedFieldSpec::Newtype { .. } => &[],
        }
    }

    /// Returns true if this field has element validators (uses `each(...)`)
    pub fn has_element_validators(&self) -> bool {
        !self.element_validators().is_empty()
    }

    /// Returns true if this field has any validators (field or element)
    pub fn has_validators(&self) -> bool {
        !self.field_validators().is_empty() || !self.element_validators().is_empty()
    }

    /// Returns true if this field is a nested Koruma struct
    pub fn is_nested(&self) -> bool {
        matches!(self.validation, ParsedFieldSpec::Nested { .. })
    }

    /// Returns true if this field is a newtype wrapper
    pub fn is_newtype(&self) -> bool {
        matches!(self.validation, ParsedFieldSpec::Newtype { .. })
    }

    /// Returns an iterator over all validator names on this field.
    pub fn validator_names(&self) -> impl Iterator<Item = &Ident> {
        self.field_validators()
            .iter()
            .chain(self.element_validators().iter())
            .map(|v| v.validator.name())
    }
}

/// Parse a single field and extract its koruma validation information.
///
/// This function handles:
/// - Multiple `#[koruma(...)]` attributes on the same field
/// - Combining validators from multiple attributes
/// - Preserving optional validator labels for downstream name generation
/// - The `skip`, `nested`, and `newtype` modifiers
///
/// # Returns
///
/// - `Ok(Some(FieldInfo))` if the field participates in validation.
/// - `Ok(None)` if the field has no koruma attributes or is marked with `skip`.
/// - `Err(Error)` if parsing failed, such as duplicate or conflicting modifiers.
pub fn parse_field(field: &Field, index: usize) -> Result<Option<FieldInfo>> {
    let (name, member) = match field.ident.clone() {
        Some(ident) => (ident.clone(), Member::Named(ident)),
        None => (
            quote::format_ident!("_{}", index),
            Member::Unnamed(Index::from(index)),
        ),
    };
    let ty = field.ty.clone();

    // Collect typed items from ALL #[koruma(...)] attributes on this field.
    let mut items = Vec::new();

    for attr in field.attrs.to_vec().find_attribute("koruma") {
        match attr.parse_args::<DataFieldKorumaAttr>() {
            Ok(koruma_attr) => items.extend(koruma_attr.items),
            Err(e) => return Err(e),
        }
    }

    let validation = normalize_field_items(field, items)?;
    if matches!(validation, None | Some(ParsedFieldSpec::Skipped)) {
        return Ok(None);
    }
    let validation = validation.expect("checked above");

    Ok(Some(FieldInfo {
        name,
        member,
        ty,
        index,
        validation,
    }))
}

fn normalize_field_items(
    field: &Field,
    items: Vec<DataFieldKorumaItem>,
) -> Result<Option<ParsedFieldSpec>> {
    let mut all_field_validators = Vec::new();
    let mut all_element_validators = Vec::new();
    let mut modifier_kind: Option<FieldModifierKind> = None;
    let mut mode_modifier: Option<FieldModifier> = None;
    let mut first_field_validator_path: Option<Path> = None;
    let mut first_element_marker: Option<Ident> = None;

    for item in items {
        match item {
            DataFieldKorumaItem::Modifier(modifier) => {
                if modifier_kind.is_some() {
                    return Err(Error::new(
                        modifier.ident.span(),
                        "duplicate or conflicting field modifier across `#[koruma(...)]` attributes",
                    ));
                }
                modifier_kind = Some(modifier.kind);
                mode_modifier = Some(modifier);
            },
            DataFieldKorumaItem::FieldValidation(spec) => {
                let validator = spec.validator;
                if first_field_validator_path.is_none() {
                    first_field_validator_path = Some(validator.validator.validator.clone());
                }
                all_field_validators.push(validator);
            },
            DataFieldKorumaItem::ElementValidation(spec) => {
                if first_element_marker.is_none() {
                    first_element_marker = Some(spec.marker.clone());
                }
                for validator in spec.validators {
                    all_element_validators.push(validator);
                }
            },
        }
    }

    if modifier_kind == Some(FieldModifierKind::Skip)
        && (!all_field_validators.is_empty() || !all_element_validators.is_empty())
    {
        return Err(Error::new(
            first_field_validator_path
                .as_ref()
                .map(Spanned::span)
                .or_else(|| first_element_marker.as_ref().map(Spanned::span))
                .unwrap_or_else(|| {
                    mode_modifier
                        .as_ref()
                        .map(|modifier| modifier.ident.span())
                        .unwrap_or_else(|| field.span())
                }),
            "fields marked `#[koruma(skip)]` cannot also use validators or `each(...)`",
        ));
    }

    if modifier_kind == Some(FieldModifierKind::Skip) {
        return Ok(Some(ParsedFieldSpec::Skipped));
    }

    if modifier_kind == Some(FieldModifierKind::Nested)
        && (!all_field_validators.is_empty() || !all_element_validators.is_empty())
    {
        return Err(Error::new(
            first_field_validator_path
                .as_ref()
                .map(Spanned::span)
                .or_else(|| first_element_marker.as_ref().map(Spanned::span))
                .unwrap_or_else(|| {
                    mode_modifier
                        .as_ref()
                        .map(|modifier| modifier.ident.span())
                        .unwrap_or_else(|| field.span())
                }),
            "fields marked `#[koruma(nested)]` cannot also use validators or `each(...)`, even across multiple `#[koruma(...)]` attributes",
        ));
    }

    if modifier_kind == Some(FieldModifierKind::Newtype) && !all_element_validators.is_empty() {
        return Err(Error::new(
            first_element_marker
                .as_ref()
                .map(Spanned::span)
                .unwrap_or_else(|| {
                    mode_modifier
                        .as_ref()
                        .map(|modifier| modifier.ident.span())
                        .unwrap_or_else(|| field.span())
                }),
            "fields marked `#[koruma(newtype)]` cannot also use `each(...)`; element validation is not supported for newtype wrappers",
        ));
    }

    // Must have at least one validator or modifier
    if modifier_kind.is_none()
        && all_field_validators.is_empty()
        && all_element_validators.is_empty()
    {
        return Ok(None);
    }

    let spec = match modifier_kind {
        Some(FieldModifierKind::Nested) => ParsedFieldSpec::Nested {
            marker: mode_modifier
                .expect("nested modifier should carry its source ident")
                .ident,
        },
        Some(FieldModifierKind::Newtype) => ParsedFieldSpec::Newtype {
            marker: mode_modifier
                .expect("newtype modifier should carry its source ident")
                .ident,
            field_validators: all_field_validators,
        },
        Some(FieldModifierKind::Skip) => ParsedFieldSpec::Skipped,
        None => ParsedFieldSpec::Regular {
            field_validators: all_field_validators,
            element_validators: all_element_validators,
        },
    };

    Ok(Some(spec))
}

/// Parsed validator-field `value` marker metadata.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ValidatorValueSpec {
    pub capture: CapturePolicy,
}

/// Default behavior requested by `#[koruma(setter(default...))]`.
#[derive(Clone, Debug)]
pub enum SetterDefault {
    None,
    Default,
    Expr(Expr),
}

/// Parsed validator-field `setter(...)` metadata.
#[derive(Clone, Debug)]
pub struct ValidatorSetterSpec {
    pub method: Ident,
    pub into: bool,
    pub required: bool,
    pub default: SetterDefault,
}

/// Typed role of a field inside a `#[koruma::validator]` struct.
#[derive(Clone, Debug)]
pub enum ValidatorFieldRole {
    Value(ValidatorValueSpec),
    Setter(ValidatorSetterSpec),
}

/// Typed metadata for one field inside a `#[koruma::validator]` struct.
#[derive(Clone, Debug)]
pub struct ValidatorFieldSpec {
    pub name: Ident,
    pub ty: Type,
    pub role: ValidatorFieldRole,
}

/// Fully parsed and normalized `#[koruma::validator]` struct-field metadata.
#[derive(Clone, Debug)]
pub struct ValidatorStructSpec {
    pub fields: Vec<ValidatorFieldSpec>,
    pub value_index: usize,
}

impl ValidatorStructSpec {
    pub fn value_field(&self) -> &ValidatorFieldSpec {
        &self.fields[self.value_index]
    }

    pub fn value_spec(&self) -> &ValidatorValueSpec {
        let ValidatorFieldRole::Value(value) = &self.value_field().role else {
            unreachable!("value_index should point at a value field")
        };
        value
    }
}

#[derive(Clone, Debug)]
pub enum ValidatorFieldKorumaItem {
    Value(ValidatorValueSpec),
    Setter(ParsedSetterOptions),
}

#[derive(Clone, Debug, Default)]
pub struct ParsedSetterOptions {
    method: Option<Ident>,
    into: bool,
    required: bool,
    default: SetterDefault,
}

#[derive(Clone, Debug)]
struct ValidatorFieldMarker {
    ident: Ident,
    item: ValidatorFieldKorumaItem,
}

#[derive(Clone, Debug, Default)]
struct ValidatorFieldKorumaAttr {
    markers: Vec<ValidatorFieldMarker>,
}

impl Default for SetterDefault {
    fn default() -> Self {
        Self::None
    }
}

impl Parse for ValidatorFieldKorumaAttr {
    fn parse(input: ParseStream) -> Result<Self> {
        let mut attr = ValidatorFieldKorumaAttr::default();

        while !input.is_empty() {
            let ident: Ident = input.parse()?;
            let item = if ident == "value" {
                let capture = if input.peek(syn::token::Paren) {
                    parse_value_capture_policy(input)?
                } else {
                    CapturePolicy::CloneInput
                };
                ValidatorFieldKorumaItem::Value(ValidatorValueSpec { capture })
            } else if ident == "skip_capture" {
                return Err(context_error(&ident, KorumaAttrContext::ValidatorField));
            } else if ident == "setter" {
                ValidatorFieldKorumaItem::Setter(parse_setter_options(input)?)
            } else {
                return Err(context_error(&ident, KorumaAttrContext::ValidatorField));
            };
            attr.markers.push(ValidatorFieldMarker { ident, item });

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            } else {
                break;
            }
        }

        Ok(attr)
    }
}

fn parse_setter_options(input: ParseStream) -> Result<ParsedSetterOptions> {
    let content;
    parenthesized!(content in input);
    let mut options = ParsedSetterOptions::default();

    while !content.is_empty() {
        let ident: Ident = content.parse()?;
        if ident == "into" {
            options.into = true;
        } else if ident == "required" {
            options.required = true;
        } else if ident == "name" {
            content.parse::<Token![=]>()?;
            options.method = Some(content.parse()?);
        } else if ident == "default" {
            options.default = if content.peek(Token![=]) {
                content.parse::<Token![=]>()?;
                SetterDefault::Expr(content.parse()?)
            } else {
                SetterDefault::Default
            };
        } else {
            return Err(Error::new(
                ident.span(),
                format!(
                    "unsupported `#[koruma(setter({ident}))]` option; supported options are `into`, `required`, `name`, and `default`"
                ),
            ));
        }

        if content.peek(Token![,]) {
            content.parse::<Token![,]>()?;
        } else {
            break;
        }
    }

    Ok(options)
}

fn parse_value_capture_policy(input: ParseStream) -> Result<CapturePolicy> {
    let content;
    parenthesized!(content in input);

    let key: Ident = content.parse()?;
    if key != "capture" {
        return Err(Error::new(
            key.span(),
            "unsupported `value(...)` option; supported option is `capture = skip`",
        ));
    }
    content.parse::<Token![=]>()?;
    let policy: Ident = content.parse()?;
    let capture = if policy == "skip" {
        CapturePolicy::Skip
    } else {
        return Err(Error::new(
            policy.span(),
            "unsupported capture policy; supported policy is `skip`",
        ));
    };

    if content.peek(Token![,]) {
        content.parse::<Token![,]>()?;
    }
    if !content.is_empty() {
        return Err(Error::new(
            content.span(),
            "unexpected extra tokens in `value(...)`; supported option is `capture = skip`",
        ));
    }

    Ok(capture)
}

fn validator_field_attr(attr: &ExpandedAttr) -> Result<ValidatorFieldKorumaAttr> {
    attr.parse_args::<ValidatorFieldKorumaAttr>()
}

/// Describes whether the `#[koruma(value)]` field should capture the input
/// value in derived validation errors.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapturePolicy {
    /// Store the validated value in the generated validator instance.
    CloneInput,
    /// Skip storing the validated value and leave the field at its default.
    Skip,
}

/// Parsed information about the field marked with `#[koruma(value)]`.
#[derive(Clone, Debug)]
pub struct ValueFieldInfo {
    pub name: Ident,
    pub ty: Type,
    pub capture: CapturePolicy,
}

/// Parse all fields in a `#[koruma::validator]` struct into typed metadata.
///
/// This strict API proves that exactly one field is marked `#[koruma(value)]`,
/// value fields do not also define setter metadata, all validator-field
/// `#[koruma(...)]` attributes use validator-field grammar, and required
/// setters are not also defaulted.
pub fn parse_validator_fields_strict(input: &ItemStruct) -> Result<ValidatorStructSpec> {
    parse_validator_fields(input, true)?.ok_or_else(|| {
        Error::new_spanned(
            input,
            "koruma::validator requires a field marked with #[koruma(value)].\n\
             Example:\n\
             #[koruma(value)]\n\
             actual: Option<i32>",
        )
    })
}

fn parse_validator_fields(
    input: &ItemStruct,
    require_value: bool,
) -> Result<Option<ValidatorStructSpec>> {
    let Fields::Named(ref fields) = input.fields else {
        return Ok(None);
    };

    let mut parsed_fields: Vec<ValidatorFieldSpec> = Vec::new();
    let mut value_index: Option<usize> = None;

    for field in &fields.named {
        let Some(field_name) = field.ident.clone() else {
            continue;
        };

        let mut value: Option<(Ident, ValidatorValueSpec)> = None;
        let mut setter = ValidatorSetterSpec {
            method: field_name.clone(),
            into: false,
            required: false,
            default: SetterDefault::None,
        };
        let mut has_setter_metadata = false;

        for attr in field.attrs.to_vec().find_attribute("koruma") {
            let markers = validator_field_attr(&attr)?;
            if markers.markers.is_empty() {
                return Err(Error::new_spanned(
                    attr.path(),
                    format!(
                        "`#[koruma(...)]` on validator fields must contain {}; data-field modifiers like `nested`, `newtype`, and validators are only valid on derive data fields",
                        KorumaAttrContext::ValidatorField.accepted_items()
                    ),
                ));
            }

            for marker in markers.markers {
                match marker.item {
                    ValidatorFieldKorumaItem::Value(value_spec) => {
                        if value.is_some() {
                            return Err(Error::new(
                                marker.ident.span(),
                                format!(
                                    "field `{field_name}` has multiple `#[koruma(value)]` markers"
                                ),
                            ));
                        }
                        value = Some((marker.ident, value_spec));
                    },
                    ValidatorFieldKorumaItem::Setter(setter_options) => {
                        has_setter_metadata = true;
                        merge_setter_options(&mut setter, setter_options);
                    },
                }
            }
        }

        if value.is_some() && has_setter_metadata {
            return Err(Error::new_spanned(
                field,
                "`#[koruma(value)]` fields cannot also use `#[koruma(setter(...))]`",
            ));
        }

        if setter.required && !matches!(setter.default, SetterDefault::None) {
            return Err(Error::new_spanned(
                field,
                "`required` and `default` cannot be combined in `#[koruma(setter(...))]`",
            ));
        }

        let role = if let Some((_, value_spec)) = value {
            if let Some(existing_index) = value_index {
                let existing = &parsed_fields[existing_index].name;
                return Err(Error::new(
                    field_name.span(),
                    format!(
                        "koruma::validator requires exactly one `#[koruma(value)]` field, found both `{}` and `{}`",
                        existing, field_name
                    ),
                ));
            }
            value_index = Some(parsed_fields.len());
            ValidatorFieldRole::Value(value_spec)
        } else {
            ValidatorFieldRole::Setter(setter)
        };

        parsed_fields.push(ValidatorFieldSpec {
            name: field_name,
            ty: field.ty.clone(),
            role,
        });
    }

    match value_index {
        Some(value_index) => Ok(Some(ValidatorStructSpec {
            fields: parsed_fields,
            value_index,
        })),
        None if require_value => Ok(None),
        None => Ok(None),
    }
}

fn merge_setter_options(setter: &mut ValidatorSetterSpec, options: ParsedSetterOptions) {
    if let Some(method) = options.method {
        setter.method = method;
    }
    setter.into |= options.into;
    setter.required |= options.required;
    if !matches!(options.default, SetterDefault::None) {
        setter.default = options.default;
    }
}

/// Find the field marked with `#[koruma(value)]` and return its parsed info.
///
/// This strict variant validates that validator structs use exactly one
/// `#[koruma(value)]` marker and that validator-field `#[koruma(...)]`
/// attributes only contain the `value`, `value(capture = skip)`, and `setter(...)` markers.
pub fn find_value_field_info_strict(input: &ItemStruct) -> Result<Option<ValueFieldInfo>> {
    Ok(parse_validator_fields(input, false)?.map(|spec| {
        let value_field = spec.value_field();
        let ValidatorFieldRole::Value(value) = &value_field.role else {
            unreachable!("value field should have value role")
        };
        ValueFieldInfo {
            name: value_field.name.clone(),
            ty: value_field.ty.clone(),
            capture: value.capture,
        }
    }))
}

/// Find the field marked with `#[koruma(value)]` and return its name and type.
///
/// This strict variant validates that validator structs use exactly one
/// `#[koruma(value)]` marker and that validator-field `#[koruma(...)]`
/// attributes only contain the `value`, `value(capture = skip)`, and `setter(...)` markers.
pub fn find_value_field_strict(input: &ItemStruct) -> Result<Option<(Ident, Type)>> {
    Ok(find_value_field_info_strict(input)?.map(|info| (info.name, info.ty)))
}

/// Parsed showcase attribute:
/// `#[showcase(name = "...", description = "...", create = |input| { ... }, input_type = Text)]`
///
/// The `create` closure takes a `&str` and returns the validator instance.
/// Required `input_type` must be `Text` or `Numeric`.
/// Optional `module` can be "string", "format", "numeric", "collection", or "general".
/// `module` defaults to `general` when omitted.
#[cfg(feature = "internal-showcase")]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ShowcaseInputType {
    /// Showcases that expect text input.
    Text,
    /// Showcases that expect numeric input.
    Numeric,
}

/// Parsed and validated `module` selector for showcase validators.
#[cfg(feature = "internal-showcase")]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ShowcaseModule {
    String,
    Format,
    Numeric,
    Collection,
    General,
}

#[cfg(feature = "internal-showcase")]
#[derive(Clone, Debug)]
pub struct ShowcaseAttr {
    pub name: syn::LitStr,
    pub description: syn::LitStr,
    pub create: syn::ExprClosure,
    pub input_type: ShowcaseInputType,
    pub module: Option<ShowcaseModule>,
}

#[cfg(feature = "internal-showcase")]
impl Parse for ShowcaseAttr {
    fn parse(input: ParseStream) -> Result<Self> {
        let mut name: Option<syn::LitStr> = None;
        let mut description: Option<syn::LitStr> = None;
        let mut create: Option<syn::ExprClosure> = None;
        let mut input_type: Option<Ident> = None;
        let mut module: Option<ShowcaseModule> = None;

        while !input.is_empty() {
            let ident: Ident = input.parse()?;
            input.parse::<Token![=]>()?;

            match ident.to_string().as_str() {
                "name" => {
                    name = Some(input.parse()?);
                },
                "description" => {
                    description = Some(input.parse()?);
                },
                "create" => {
                    create = Some(input.parse()?);
                },
                "input_type" => {
                    input_type = Some(input.parse()?);
                },
                "module" => {
                    let parsed_module: syn::LitStr = input.parse()?;
                    module = Some(parse_showcase_module(parsed_module)?);
                },
                other => {
                    return Err(Error::new(
                        ident.span(),
                        format!("unknown showcase attribute: {}", other),
                    ));
                },
            }

            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        Ok(ShowcaseAttr {
            name: name
                .ok_or_else(|| Error::new(input.span(), "showcase requires `name` attribute"))?,
            description: description.ok_or_else(|| {
                Error::new(input.span(), "showcase requires `description` attribute")
            })?,
            create: create
                .ok_or_else(|| Error::new(input.span(), "showcase requires `create` attribute"))?,
            input_type: match input_type {
                Some(input_type) => parse_showcase_input_type(input_type)?,
                None => {
                    return Err(Error::new(
                        input.span(),
                        "showcase requires `input_type` attribute",
                    ));
                },
            },
            module,
        })
    }
}

#[cfg(feature = "internal-showcase")]
fn parse_showcase_input_type(input_type: Ident) -> Result<ShowcaseInputType> {
    match input_type.to_string().as_str() {
        "Text" => Ok(ShowcaseInputType::Text),
        "Numeric" => Ok(ShowcaseInputType::Numeric),
        _ => Err(Error::new(
            input_type.span(),
            "showcase `input_type` must be `Text` or `Numeric`",
        )),
    }
}

#[cfg(feature = "internal-showcase")]
fn parse_showcase_module(module: syn::LitStr) -> Result<ShowcaseModule> {
    match module.value().as_str() {
        "string" => Ok(ShowcaseModule::String),
        "format" => Ok(ShowcaseModule::Format),
        "numeric" => Ok(ShowcaseModule::Numeric),
        "collection" => Ok(ShowcaseModule::Collection),
        "general" => Ok(ShowcaseModule::General),
        _ => Err(Error::new(
            module.span(),
            "showcase `module` must be one of: \"string\", \"format\", \"numeric\", \"collection\", or \"general\"",
        )),
    }
}

/// Find and parse showcase attribute from struct
#[cfg(feature = "internal-showcase")]
pub fn find_showcase_attr(input: &ItemStruct) -> Result<Option<ShowcaseAttr>> {
    for attr in &input.attrs {
        if attr.path().is_ident("showcase") {
            return Ok(Some(attr.parse_args::<ShowcaseAttr>()?));
        }
    }
    Ok(None)
}
