[package]
name = "koruma"
description = """
The koruma crate
"""
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
inventory = { optional = true, workspace = true }
koruma-core = { workspace = true }
koruma-derive = { optional = true, workspace = true }

[features]
default = [ "derive" ]
derive = [ "dep:koruma-derive" ]
fluent = [ "koruma-core/fluent", "koruma-derive?/fluent" ]
internal-showcase = [
  "dep:inventory",
  "koruma-core/internal-showcase",
  "koruma-derive?/internal-showcase",
]

[package.metadata.docs.rs]
features = [ "derive", "fluent" ]
