[package]
name = "koruma-collection"
description = """
A collection of common validators using koruma.
"""
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
anyhow = { optional = true, workspace = true }
card-validate = { optional = true, workspace = true }
es-fluent = { features = [ "derive" ], optional = true, workspace = true }
es-fluent-manager-embedded = { optional = true, workspace = true }
email_address = { optional = true, workspace = true }
koruma = { workspace = true }
phonenumber = { optional = true, workspace = true }
regex = { optional = true, workspace = true }
rust_decimal = { optional = true, workspace = true }
rust-embed = { optional = true, workspace = true }
url = { optional = true, workspace = true }
smallvec = { optional = true, workspace = true }

[build-dependencies]
es-fluent = { features = [ "build" ], workspace = true }

[features]
default = [ "fmt" ]
full = [ "url", "credit-card", "phone-number", "email", "regex", "smallvec", "rust_decimal" ]
full-fluent = [ "full", "fluent" ]
fluent = [ "koruma/fluent", "dep:es-fluent", "dep:es-fluent-manager-embedded", "dep:rust-embed" ]
internal-showcase = [ "full-fluent", "koruma/internal-showcase", "fmt", "dep:anyhow" ]
credit-card = [ "dep:card-validate" ]
rust_decimal = [ "dep:rust_decimal" ]
email = [ "dep:email_address" ]
smallvec = [ "dep:smallvec" ]
fmt = [  ]
phone-number = [ "dep:phonenumber" ]
regex = [ "dep:regex" ]
url = [ "dep:url" ]

[package.metadata.docs.rs]
features = [
  "full",
  "full-fluent",
  "fluent",
  "credit-card",
  "rust_decimal",
  "email",
  "smallvec",
  "fmt",
  "phone-number",
  "regex",
  "url",
]

[package.metadata.cargo-machete]
ignored = [ "rust-embed" ]
