[package]
name = "collection-ratatui-web"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
collection-ratatui-core = { path = "../collection-ratatui-core" }
console_error_panic_hook = { workspace = true }
ratatui = { workspace = true }
ratzilla = { workspace = true }
wasm-bindgen = { workspace = true }
