[package]
name = "readme"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-manager-embedded = { workspace = true }
koruma = { features = [ "derive", "fluent" ], workspace = true }
koruma-shared-lib = { path = "../shared-lib" }
rust-embed = { workspace = true }
strum = { features = [ "derive" ], workspace = true }
koruma-collection = { features = [ "full" ], workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }

[package.metadata.cargo-machete]
ignored = [ "rust-embed" ]
