[package]
name = "koruma-derive-fixtures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
fluent = ["koruma-derive/fluent"]
internal-showcase = ["koruma-derive/internal-showcase"]

[dev-dependencies]
es-fluent = { workspace = true }
koruma-derive = { features = ["fluent"], workspace = true }
renamed-koruma = { default-features = false, features = [
  "fluent",
], package = "koruma", path = "../../crates/koruma", version = "0.12.1" }
trybuild = { workspace = true }

[lints]
workspace = true
