[book]
title = "Koruma Documentation"
authors = ["stayhydated"]
language = "en"
src = "src"

[rust]
edition = "2024"

[build]

[preprocessor.admonish]
optional = true

[output.html]
additional-css = ["theme/oled-neon.css"]
