[package]
name = "collection-ratatui-native"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
collection-ratatui-core = { path = "../collection-ratatui-core" }
crossterm = { workspace = true }
ratatui = { features = [ "crossterm" ], workspace = true }
