[package]
name = "web"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[features]
default = [ "web" ]
web = [ "dioxus/web", "stayhydated-site/web" ]

[dependencies]
bon = { workspace = true }
dioxus = { features = [ "router", "launch", "lib" ], workspace = true }
dioxus-free-icons = { features = [ "lucide" ], workspace = true }
dioxus-primitives = { features = [ "router" ], workspace = true }
es-fluent = { workspace = true }
es-fluent-lang = { workspace = true }
es-fluent-manager-dioxus = { features = [ "client", "ssr" ], workspace = true }
es-fluent-manager-embedded = { workspace = true }
koruma = { features = [ "internal-showcase", "derive", "fluent" ], workspace = true }
koruma-collection = { features = [ "internal-showcase" ], workspace = true }
stayhydated-dioxus = { workspace = true }
stayhydated-site = { workspace = true }
strum = { features = [ "derive" ], workspace = true }
unic-langid = { workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }

[dev-dependencies]
dioxus = { features = [ "ssr" ], workspace = true }

[lints]
workspace = true
